// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $find from "./routes/find.ts";
import * as $index from "./routes/index.tsx";
import * as $SearchFIeld from "./islands/SearchFIeld.tsx";
import * as $useDebounce from "./islands/useDebounce.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/find.ts": $find,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/SearchFIeld.tsx": $SearchFIeld,
    "./islands/useDebounce.ts": $useDebounce,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
